[overlay]
layer = "background"
anchor_margin = 10
width = 1000
height = 300

[visualizer]
backend = "cava" # cava it's better for bars and pipewire for wave
type = "bar"
bars = 120
bar_width = 12
bar_corner_radius = 20
gap = 5
wave_thickness = 2
framerate = 60
gpu = "enabled"

[daemon]
enabled = true
poll_interval_ms = 90
activity_threshold = 0.035
activate_delay_ms = 180
deactivate_delay_ms = 2200
stop_on_silence = true
notify_on_error = true
notify_cooldown_seconds = 45
allowed_processes = ["spotify", "firefox"]
overlay_command = "cavaii"
overlay_args = []
